name: api-teams-soccer.deployment

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Building the application"
    
    deploy-dev:
        runs-on: ubuntu-latest
        environment:
            name: DEV_AWS
            url: ${{ vars.URL }} 
        needs: build
        steps:
            - name: Repo Checkout
              uses: actions/checkout@v3  
            - name: Adjust Permissions
              run: chmod -R 755 ./vendor ./bootstrap/cache ./storage
            - name: Deploy to DEV in AWS
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                ARGS: "-rltgoDzvO --delete"
                SOURCE: "./"
                REMOTE_HOST: ${{ vars.REMOTE_HOST }}
                REMOTE_USER: ${{ vars.REMOTE_USER }}
                REMOTE_PORT: ${{ vars.REMOTE_PORT }}
                TARGET: ${{ vars.TARGET }}
